apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mgnblack/cloud-storage-front-end:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      