apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  REDIS_PASSWORD: cGFzc3dvcmQ=
  MINIO_ROOT_USER: dXNlcg==
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=