apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  POSTGRES_DB: cloud-storage-db
  DATABASE_URL: jdbc:postgresql://svc-postgres/cloud-storage-db
  REDIS_URL: svc-redis
  MINIO_URL: http://svc-minio:9000