-- liquibase formatted sql

-- changeset red-eyed:create-table-resources

CREATE TABLE resources
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    path    VARCHAR(3000) NOT NULL,
    name    VARCHAR(200) NOT NULL,
    size    BIGINT,
    type    RESOURCE_TYPE NOT NULL

    CONSTRAINT check_path CHECK (path ~ '^(?:\/|(?:[^\/\\:*?"<>|]+\/)+)$')
    CONSTRAINT check_name CHECK (name ~ '^[^\/\\:*?"<>|]+$')
    CONSTRAINT check_size CHECK (type = 'DIRECTORY' OR (size IS NOT NULL AND size > 0))
);

CREATE UNIQUE INDEX unique_index_userId_path_name_type
ON resources (user_id, path, name, type);